### PR TITLE
improve performance

### PR DESCRIPTION
**Pull request by bprodoehl**
I noticed after going from 0.3.1 to 0.3.2, that performance of random and pseudo modes dropped by 50%!  It looks like readable-stream 1.1.0 is to blame.

| mode | 0.3.1 | 0.3.2 | PR |
| --- | --- | --- | --- |
| random | 400Mbps | 197Mbps | 453Mbps |
| pseudo | 382Mbps | 202Mbps | 451Mbps |
| 0 | 845Mbps | 810Mbps | 822Mbps |
| alpha | -- | 263Mbps | 256Mbps |
| num | -- | 244Mbps | 241Mbps |
| pregenerated | -- | 785Mbps | 845Mbps |

I don't know why, and haven't looked around for readable-stream issues that may be related, but just dropping back from 1.1.0 to 1.0.x fixes it.  I also tweaked the pregenerated mode for speed, but it comes at the cost of being vulnerable to downstream consumers writing to the returned data.  For that reason, I left both behaviors in there, with only the faster behavior active.

### CODE REVIEW

**Comment by chakrit** [comment]
Awesome : ) Are you actively using this in a production environment? I rarely touch this codebase nowadays, just `npm i`-ing it from time to time on some of the servers to test things.

**Comment by chakrit** [comment]
Would you like commit access & npm pub rights?

**Comment by bprodoehl** [comment]
Hey, sorry for the delayed reply.  Yes, we are using this in a production environment, as part of some speed tests between client software and our servers.   We're also using it internally for some transport protocol speed tests.  I like it because I can fetch a 10GB pseudorandom file without needing to actually create a 10GB file somewhere.  I don't anticipate bugging you with more changes down the road, but sure, I'd take commit access and npm pub rights.

I think the only remaining thing is I'd like to wrap it with something that knows how much data it is supposed to emit, and will signal an end-of-stream when it is "empty".  I think that would work best as something additional in the stream chain with randstream, and not as part of randstream itself, but I haven't figured out a good way to do that yet.

**Comment by chakrit** [comment]
What's your npm username?

**Pull request closed without merging**
